name = "car-qrcode-notify"
main = "worker.js"
compatibility_date = "2025-08-17"

[[d1_databases]]
binding = "DB"
database_name = "movecar-db"
database_id = "095826e7-8f2b-4a6e-a97a-ef64a6b53a18"